 API fetching & pagination logic

In [43]:
import pandas as pd
import requests

In [44]:
response=requests.get("https://api.freeapi.app/api/v1/public/stocks")
response.json()

{'statusCode': 200,
 'data': {'page': 1,
  'limit': 10,
  'totalPages': 191,
  'previousPage': False,
  'nextPage': True,
  'totalItems': 1906,
  'currentPageItems': 10,
  'data': [{'Name': '20 Microns Limited',
    'Symbol': '20MICRONS',
    'ListingDate': '06-Oct-08',
    'ISIN': 'INE144J01027',
    'MarketCap': '₹ 621 Cr.',
    'CurrentPrice': '₹ 176',
    'HighLow': '₹ 201 / 62.8',
    'StockPE': '12.8',
    'BookValue': '₹ 91.1',
    'DividendYield': '0.42 %',
    'ROCE': '19.3 %',
    'ROE': '15.3 %',
    'FaceValue': '₹ 5.00'},
   {'Name': '21st Century Management Services Limited',
    'Symbol': '21STCENMGM',
    'ListingDate': '03-May-95',
    'ISIN': 'INE253B01015',
    'MarketCap': '₹ 34.4 Cr.',
    'CurrentPrice': '₹ 32.8',
    'HighLow': '₹ 33.5 / 16.5',
    'StockPE': '',
    'BookValue': '₹ 26.4',
    'DividendYield': '0.00 %',
    'ROCE': '-57.7 %',
    'ROE': '-70.6 %',
    'FaceValue': '₹ 10.0'},
   {'Name': '360 ONE WAM LIMITED',
    'Symbol': '360ONE',
    'ListingDate': '19-Sep-19',
    'ISIN': 'INE466L01038',
    'MarketCap': '₹ 24,716 Cr.',
    'CurrentPrice': '₹ 690',
    'HighLow': '₹ 735 / 395',
    'StockPE': '35.5',
    'BookValue': '₹ 91.4',
    'DividendYield': '2.49 %',
    'ROCE': '13.4 %',
    'ROE': '21.4 %',
    'FaceValue': '₹ 1.00'},
   {'Name': '3i Infotech Limited',
    'Symbol': '3IINFOLTD',
    'ListingDate': '22-Oct-21',
    'ISIN': 'INE748C01038',
    'MarketCap': '₹ 839 Cr.',
    'CurrentPrice': '₹ 49.7',
    'HighLow': '₹ 51.0 / 25.9',
    'StockPE': '',
    'BookValue': '₹ 25.2',
    'DividendYield': '0.00 %',
    'ROCE': '2.59 %',
    'ROE': '0.45 %',
    'FaceValue': '₹ 10.0'},
   {'Name': '3M India Limited',
    'Symbol': '3MINDIA',
    'ListingDate': '13-Aug-04',
    'ISIN': 'INE470A01017',
    'MarketCap': '₹ 40,714 Cr.',
    'CurrentPrice': '₹ 36,126',
    'HighLow': '₹ 37,475 / 21,300',
    'StockPE': '76.0',
    'BookValue': '₹ 1,634',
    'DividendYield': '0.28 %',
    'ROCE': '31.4 %',
    'ROE': '23.4 %',
    'FaceValue': '₹ 10.0'},
   {'Name': '3P Land Holdings Limited',
    'Symbol': '3PLAND',
    'ListingDate': '19-Jul-95',
    'ISIN': 'INE105C01023',
    'MarketCap': '₹ 47.7 Cr.',
    'CurrentPrice': '₹ 26.5',
    'HighLow': '₹ 36.8 / 16.2',
    'StockPE': '29.6',
    'BookValue': '₹ 47.3',
    'DividendYield': '0.00 %',
    'ROCE': '3.07 %',
    'ROE': '2.32 %',
    'FaceValue': '₹ 2.00'},
   {'Name': '5Paisa Capital Limited',
    'Symbol': '5PAISA',
    'ListingDate': '16-Nov-17',
    'ISIN': 'INE618L01018',
    'MarketCap': '₹ 1,751 Cr.',
    'CurrentPrice': '₹ 563',
    'HighLow': '₹ 566 / 270',
    'StockPE': '29.7',
    'BookValue': '₹ 163',
    'DividendYield': '0.00 %',
    'ROCE': '12.4 %',
    'ROE': '10.6 %',
    'FaceValue': '₹ 10.0'},
   {'Name': '63 moons technologies limited',
    'Symbol': '63MOONS',
    'ListingDate': '20-Jun-05',
    'ISIN': 'INE111B01023',
    'MarketCap': '₹ 2,180 Cr.',
    'CurrentPrice': '₹ 473',
    'HighLow': '₹ 691 / 158',
    'StockPE': '17.1',
    'BookValue': '₹ 704',
    'DividendYield': '0.42 %',
    'ROCE': '1.99 %',
    'ROE': '-1.43 %',
    'FaceValue': '₹ 2.00'},
   {'Name': 'A2Z Infra Engineering Limited',
    'Symbol': 'A2ZINFRA',
    'ListingDate': '23-Dec-10',
    'ISIN': 'INE619I01012',
    'MarketCap': '₹ 206 Cr.',
    'CurrentPrice': '₹ 11.7',
    'HighLow': '₹ 12.6 / 5.10',
    'StockPE': '',
    'BookValue': '₹ 2.01',
    'DividendYield': '0.00 %',
    'ROCE': '6.57 %',
    'ROE': '15.7 %',
    'FaceValue': '₹ 10.0'},
   {'Name': 'AAA Technologies Limited',
    'Symbol': 'AAATECH',
    'ListingDate': '28-Nov-22',
    'ISIN': 'INE0D0U01013',
    'MarketCap': '₹ Cr.',
    'CurrentPrice': '₹',
    'HighLow': '₹ /',
    'StockPE': '',
    'BookValue': '₹',
    'DividendYield': '%',
    'ROCE': '%',
    'ROE': '%',
    'FaceValue': '₹'}]},
 'message': 'Stocks fetched successfully',
 'success': True}

In [45]:
pd.DataFrame(response.json()['data']['data'])

,Name,Symbol,ListingDate,ISIN,MarketCap,CurrentPrice,HighLow,StockPE,BookValue,DividendYield,ROCE,ROE,FaceValue
0,20 Microns Limited,20MICRONS,06-Oct-08,INE144J01027,₹ 621 Cr.,₹ 176,₹ 201 / 62.8,12.8,₹ 91.1,0.42 %,19.3 %,15.3 %,₹ 5.00
1,21st Century Management Services Limited,21STCENMGM,03-May-95,INE253B01015,₹ 34.4 Cr.,₹ 32.8,₹ 33.5 / 16.5,,₹ 26.4,0.00 %,-57.7 %,-70.6 %,₹ 10.0
2,360 ONE WAM LIMITED,360ONE,19-Sep-19,INE466L01038,"₹ 24,716 Cr.",₹ 690,₹ 735 / 395,35.5,₹ 91.4,2.49 %,13.4 %,21.4 %,₹ 1.00
3,3i Infotech Limited,3IINFOLTD,22-Oct-21,INE748C01038,₹ 839 Cr.,₹ 49.7,₹ 51.0 / 25.9,,₹ 25.2,0.00 %,2.59 %,0.45 %,₹ 10.0
4,3M India Limited,3MINDIA,13-Aug-04,INE470A01017,"₹ 40,714 Cr.","₹ 36,126","₹ 37,475 / 21,300",76.0,"₹ 1,634",0.28 %,31.4 %,23.4 %,₹ 10.0
5,3P Land Holdings Limited,3PLAND,19-Jul-95,INE105C01023,₹ 47.7 Cr.,₹ 26.5,₹ 36.8 / 16.2,29.6,₹ 47.3,0.00 %,3.07 %,2.32 %,₹ 2.00
6,5Paisa Capital Limited,5PAISA,16-Nov-17,INE618L01018,"₹ 1,751 Cr.",₹ 563,₹ 566 / 270,29.7,₹ 163,0.00 %,12.4 %,10.6 %,₹ 10.0
7,63 moons technologies limited,63MOONS,20-Jun-05,INE111B01023,"₹ 2,180 Cr.",₹ 473,₹ 691 / 158,17.1,₹ 704,0.42 %,1.99 %,-1.43 %,₹ 2.00
8,A2Z Infra Engineering Limited,A2ZINFRA,23-Dec-10,INE619I01012,₹ 206 Cr.,₹ 11.7,₹ 12.6 / 5.10,,₹ 2.01,0.00 %,6.57 %,15.7 %,₹ 10.0
9,AAA Technologies Limited,AAATECH,28-Nov-22,INE0D0U01013,₹ Cr.,₹,₹ /,,₹,%,%,%,₹

In [80]:
all_stock=[]
for i in range(192):
    response=requests.get("https://api.freeapi.app/api/v1/public/stocks",params={
        'page':i})
    if response.status_code==200:
        page_data=response.json()['data']['data']
        all_stock.extend(page_data)
    else:
        print(f"failed fetch page{i}")    
   
df_stock=pd.DataFrame(all_stock)
df_stock

,Name,Symbol,ListingDate,ISIN,MarketCap,CurrentPrice,HighLow,StockPE,BookValue,DividendYield,ROCE,ROE,FaceValue,status
0,20 Microns Limited,20MICRONS,06-Oct-08,INE144J01027,₹ 621 Cr.,₹ 176,₹ 201 / 62.8,12.8,₹ 91.1,0.42 %,19.3 %,15.3 %,₹ 5.00,NaN
1,21st Century Management Services Limited,21STCENMGM,03-May-95,INE253B01015,₹ 34.4 Cr.,₹ 32.8,₹ 33.5 / 16.5,,₹ 26.4,0.00 %,-57.7 %,-70.6 %,₹ 10.0,NaN
2,360 ONE WAM LIMITED,360ONE,19-Sep-19,INE466L01038,"₹ 24,716 Cr.",₹ 690,₹ 735 / 395,35.5,₹ 91.4,2.49 %,13.4 %,21.4 %,₹ 1.00,NaN
3,3i Infotech Limited,3IINFOLTD,22-Oct-21,INE748C01038,₹ 839 Cr.,₹ 49.7,₹ 51.0 / 25.9,,₹ 25.2,0.00 %,2.59 %,0.45 %,₹ 10.0,NaN
4,3M India Limited,3MINDIA,13-Aug-04,INE470A01017,"₹ 40,714 Cr.","₹ 36,126","₹ 37,475 / 21,300",76.0,"₹ 1,634",0.28 %,31.4 %,23.4 %,₹ 10.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1901,Zota Health Care LImited,ZOTA,19-Aug-19,INE358U01012,"₹ 1,233 Cr.",₹ 477,₹ 533 / 270,,₹ 39.5,0.21 %,-2.32 %,-7.42 %,₹ 10.0,NaN
1902,Zuari Agro Chemicals Limited,ZUARI,27-Nov-12,INE840M01016,₹ 785 Cr.,₹ 187,₹ 198 / 116,2.13,₹ 379,0.00 %,10.2 %,12.8 %,₹ 10.0,NaN
1903,ZUARI INDUSTRIES LIMITED,ZUARIIND,12-Apr-95,INE217A01012,₹ 590 Cr.,₹ 198,₹ 218 / 104,36.0,₹ 861,0.50 %,10.7 %,11.4 %,₹ 10.0,NaN
1904,Zydus Lifesciences Limited,ZYDUSLIFE,18-Apr-00,INE010B01027,"₹ 69,361 Cr.",₹ 685,₹ 697 / 413,22.2,₹ 185,0.86 %,15.0 %,13.7 %,₹ 1.00,NaN
1905,Zydus Wellness Limited,ZYDUSWELL,13-Nov-09,INE768C01010,"₹ 10,628 Cr.","₹ 1,670","₹ 1,694 / 1,364",35.2,₹ 818,0.30 %,5.93 %,6.40 %,₹ 10.0,NaN

In [81]:
df_stock.info()
df_stock.head()

<class 'pandas.DataFrame'>
RangeIndex: 1906 entries, 0 to 1905
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           1904 non-null   str
 1   Symbol         1906 non-null   str
 2   ListingDate    1904 non-null   str
 3   ISIN           1904 non-null   str
 4   MarketCap      1904 non-null   str
 5   CurrentPrice   1904 non-null   str
 6   HighLow        1904 non-null   str
 7   StockPE        1904 non-null   str
 8   BookValue      1904 non-null   str
 9   DividendYield  1904 non-null   str
 10  ROCE           1904 non-null   str
 11  ROE            1904 non-null   str
 12  FaceValue      1904 non-null   str
 13  status         2 non-null      str
dtypes: str(14)
memory usage: 208.6 KB

,Name,Symbol,ListingDate,ISIN,MarketCap,CurrentPrice,HighLow,StockPE,BookValue,DividendYield,ROCE,ROE,FaceValue,status
0,20 Microns Limited,20MICRONS,06-Oct-08,INE144J01027,₹ 621 Cr.,₹ 176,₹ 201 / 62.8,12.8,₹ 91.1,0.42 %,19.3 %,15.3 %,₹ 5.00,NaN
1,21st Century Management Services Limited,21STCENMGM,03-May-95,INE253B01015,₹ 34.4 Cr.,₹ 32.8,₹ 33.5 / 16.5,,₹ 26.4,0.00 %,-57.7 %,-70.6 %,₹ 10.0,NaN
2,360 ONE WAM LIMITED,360ONE,19-Sep-19,INE466L01038,"₹ 24,716 Cr.",₹ 690,₹ 735 / 395,35.5,₹ 91.4,2.49 %,13.4 %,21.4 %,₹ 1.00,NaN
3,3i Infotech Limited,3IINFOLTD,22-Oct-21,INE748C01038,₹ 839 Cr.,₹ 49.7,₹ 51.0 / 25.9,,₹ 25.2,0.00 %,2.59 %,0.45 %,₹ 10.0,NaN
4,3M India Limited,3MINDIA,13-Aug-04,INE470A01017,"₹ 40,714 Cr.","₹ 36,126","₹ 37,475 / 21,300",76.0,"₹ 1,634",0.28 %,31.4 %,23.4 %,₹ 10.0,NaN

DATA CLEANING

In [82]:
df_stock.columns

#droping ISIN columns 
df_stock.drop(columns='ISIN', inplace=True )

In [83]:
#columns Renaming  into snake_case
df_stock = df_stock.rename(columns={
    'Name': 'name',
    'Symbol': 'symbol',
    'ListingDate': 'listing_date',
    'MarketCap': 'market_cap',
    'CurrentPrice': 'current_price',
    'HighLow': 'high_low',
    'StockPE': 'stock_pe',
    'BookValue':'book_value',
    'DividendYield':'dividend_yield',
    'ROCE':'roce',
    'ROE':'roe',
    'FaceValue':'face_value',
})

In [140]:
# using list comprehention  exract symbol only 
df_stock.sample(3)
df_stock['symbol']=[symbol.strip('0123456789') for symbol in df_stock['symbol']]
df_stock.info()

<class 'pandas.DataFrame'>
Index: 1904 entries, 0 to 1905
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1904 non-null   str
 1   symbol          1904 non-null   str
 2   listing_date    1904 non-null   str
 3   market_cap      1904 non-null   str
 4   current_price   1904 non-null   float64
 5   high_low        1904 non-null   str
 6   stock_pe        1904 non-null   str
 7   book_value      1904 non-null   str
 8   dividend_yield  1904 non-null   str
 9   roce            1904 non-null   str
 10  roe             1904 non-null   str
 11  face_value      1904 non-null   str
 12  status          0 non-null      str
dtypes: float64(1), str(12)
memory usage: 208.2 KB

In [ ]:
# stripe -> space , symbole and comma  and covert into float

df_stock
df_stock['current_price']=df_stock.current_price.str.replace(",","").str.replace("₹","")
# converting into float and also dealing with empty string 
df_stock['current_price']=pd.to_numeric(df_stock['current_price'],errors='coerce').fillna(0.0)


df_stock['book_value']=df_stock.book_value.str.replace(",","").str.replace("₹","")
df_stock['book_value']=pd.to_numeric(df_stock['book_value'],errors='coerce').fillna(0.0)

df_stock['face_value']=df_stock.face_value.str.replace(",","").str.replace("₹","")
df_stock['face_value']=pd.to_numeric(df_stock['face_value'],errors='coerce').fillna(0.0)

In [143]:
df_stock.info()

<class 'pandas.DataFrame'>
Index: 1904 entries, 0 to 1905
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            1904 non-null   str
 1   symbol          1904 non-null   str
 2   listing_date    1904 non-null   str
 3   market_cap      1904 non-null   str
 4   current_price   1904 non-null   float64
 5   high_low        1904 non-null   str
 6   stock_pe        1904 non-null   str
 7   book_value      1904 non-null   float64
 8   dividend_yield  1904 non-null   str
 9   roce            1904 non-null   str
 10  roe             1904 non-null   str
 11  face_value      1904 non-null   float64
 12  status          0 non-null      str
dtypes: float64(3), str(10)
memory usage: 208.2 KB